const NEWLINE = '\n';

export function CANVAS_VIEW(tabString: string): string {
    const _ = tabString;
    const lines: string[] = [];
    lines.push("import { Model } from './model'");
    lines.push("");
    lines.push("/**");
    lines.push(" *");
    lines.push(" */");
    lines.push("export class View {");
    lines.push(_ + "private canvas: HTMLCanvasElement");
    lines.push(_ + "private context: CanvasRenderingContext2D");
    lines.push(_ + "/**");
    lines.push(_ + " *");
    lines.push(_ + " */");
    lines.push(_ + "constructor(private model: Model, container: HTMLElement, width = 500, height = 500) {");
    lines.push(_ + _ + "this.canvas = document.createElement('canvas')");
    lines.push(_ + _ + "this.canvas.width = width");
    lines.push(_ + _ + "this.canvas.height = height");
    lines.push(_ + _ + "container.appendChild(this.canvas)");
    lines.push(_ + _ + "this.context = this.canvas.getContext('2d') as CanvasRenderingContext2D");
    lines.push(_ + "}");
    lines.push(_ + "/**");
    lines.push(_ + " *");
    lines.push(_ + " */");
    lines.push(_ + "draw(): void {");
    lines.push(_ + _ + "this.clearCanvas()");
    lines.push(_ + _ + "this.drawBackground()");
    lines.push(_ + _ + "this.drawBody()");
    lines.push(_ + "}");
    lines.push(_ + "/**");
    lines.push(_ + " *");
    lines.push(_ + " */");
    lines.push(_ + "private clearCanvas(): void {");
    lines.push(_ + _ + "const context = this.context");
    lines.push(_ + _ + "context.clearRect(0, 0, this.canvas.width, this.canvas.height)");
    lines.push(_ + "}");
    lines.push(_ + "/**");
    lines.push(_ + " *");
    lines.push(_ + " */");
    lines.push(_ + "private drawBackground(): void {");
    lines.push(_ + _ + "const canvas = this.canvas");
    lines.push(_ + _ + "const context = this.context");
    lines.push(_ + _ + "context.fillStyle = 'gray'");
    lines.push(_ + _ + "context.fillRect(0, 0, canvas.width, canvas.height)");
    lines.push(_ + "}");
    lines.push(_ + "/**");
    lines.push(_ + " *");
    lines.push(_ + " */");
    lines.push(_ + "private drawBody(): void {");
    lines.push(_ + _ + "const body = this.model.body");
    lines.push(_ + _ + "const context = this.context");
    lines.push(_ + _ + "context.fillStyle = 'red'");
    lines.push(_ + _ + "context.fillRect(body.position.x, body.position.y, 20, 20)");
    lines.push(_ + "}");
    lines.push("}");
    return lines.join(NEWLINE).concat(NEWLINE);
}
