const NEWLINE = '\n';

export function EIGHT_VIEW(tabString: string): string {
    const _ = tabString;
    const lines: string[] = [];
    lines.push("import { Geometric3, Color } from 'davinci-eight'");
    lines.push("import { Engine, Capability } from 'davinci-eight'");
    lines.push("import { Facet, PerspectiveCamera, DirectionalLight } from 'davinci-eight'");
    lines.push("import { TrackballControls } from 'davinci-eight'");
    lines.push("import { Box } from 'davinci-eight'");
    lines.push("import { Model } from './model'");
    lines.push("");
    lines.push("const e2 = Geometric3.e2(true)");
    lines.push("const e3 = Geometric3.e3(true)");
    lines.push("");
    lines.push("/**");
    lines.push(" *");
    lines.push(" */");
    lines.push("export class View {");
    lines.push(_ + "private engine: Engine");
    lines.push(_ + "private camera: PerspectiveCamera");
    lines.push(_ + "private trackball: TrackballControls");
    lines.push(_ + "private dirLight: DirectionalLight");
    lines.push(_ + "private ambients: Facet[] = []");
    lines.push(_ + "private box: Box");
    lines.push(_ + "/**");
    lines.push(_ + " *");
    lines.push(_ + " */");
    lines.push(_ + "constructor(private model: Model, canvas: string | HTMLCanvasElement) {");
    lines.push(_ + _ + "this.engine = new Engine(canvas)");
    lines.push(_ + _ + _ + ".size(500, 500)");
    lines.push(_ + _ + _ + ".clearColor(0.1, 0.1, 0.1, 1.0)");
    lines.push(_ + _ + _ + ".enable(Capability.DEPTH_TEST)");
    lines.push("");
    lines.push(_ + _ + "this.camera = new PerspectiveCamera()");
    lines.push(_ + _ + "this.camera.eye = e2 + 3 * e3");
    lines.push(_ + _ + "this.ambients.push(this.camera)");
    lines.push("");
    lines.push(_ + _ + "this.dirLight = new DirectionalLight()");
    lines.push(_ + _ + "this.ambients.push(this.dirLight)");
    lines.push("");
    lines.push(_ + _ + "this.trackball = new TrackballControls(this.camera)");
    lines.push(_ + _ + "this.trackball.subscribe(this.engine.canvas)");
    lines.push("");
    lines.push(_ + _ + "this.box = new Box(this.engine, { color: Color.blue })");
    lines.push(_ + "}");
    lines.push(_ + "/**");
    lines.push(_ + " *");
    lines.push(_ + " */");
    lines.push(_ + "render() {");
    lines.push(_ + _ + "this.engine.clear()");
    lines.push("");
    lines.push(_ + _ + "this.trackball.update()");
    lines.push("");
    lines.push(_ + _ + "this.dirLight.direction.copyVector(this.camera.look).subVector(this.camera.eye)");
    lines.push("");
    lines.push(_ + _ + "this.box.attitude.rotorFromAxisAngle(e2, this.model.timestamp * 0.001)");
    lines.push("");
    lines.push(_ + _ + "this.box.render(this.ambients)");
    lines.push(_ + "}");
    lines.push("}");
    return lines.join(NEWLINE).concat(NEWLINE);
}
