export default function(width: number, height: number, canvasId: string): string {
    const lines = [
        "//",
        "// Using the WebGLRenderer class for flexible development.",
        "//",
        "EIGHT.refChange('start')",
        "",
        "const renderer = new EIGHT.WebGLRenderer()",
        "renderer.clearColor(0.1, 0.1, 0.1, 1.0)",
        "",
        "const scene = new EIGHT.Scene()",
        "scene.subscribe(renderer)",
        "",
        "const ambients: EIGHT.Facet[] = []",
        "",
        "const camera = new EIGHT.PerspectiveCamera(45 * Math.PI / 180, 1, 0.1, 1000)",
        "camera.position.copy(7 * e3 + e2)",
        "ambients.push(camera)",
        "",
        "const ambLight = new EIGHT.AmbientLight(EIGHT.Color.fromRGB(0.3, 0.3, 0.3))",
        "ambients.push(ambLight)",
        "",
        "const dirLight = new EIGHT.DirectionalLight(-e3, EIGHT.Color.white)",
        "ambients.push(dirLight)",
        "",
        "const controls = new EIGHT.CameraControls(camera)",
        "controls.rotateSpeed = 6",
        "controls.zoomSpeed = 4",
        "",
        "const arrow = new EIGHT.Arrow()",
        "arrow.name = 'arrow'",
        "arrow.color = EIGHT.Color.fromRGB(0.6, 0.6, 0.6)",
        "arrow.length = 1",
        "scene.add(arrow)",
        "",
        "const cube = new EIGHT.Box()",
        "cube.name = 'cube'",
        "cube.color = EIGHT.Color.green",
        "cube.width = 0.2",
        "cube.height = 1",
        "cube.depth = 1",
        "cube.position = 1.2 * e1",
        "scene.add(cube)",
        "",
        "const ball = new EIGHT.Sphere()",
        "ball.name = 'ball'",
        "ball.color = EIGHT.Color.blue",
        "ball.radius = 0.1",
        "scene.add(ball)",
        "",
        "const trail = new EIGHT.Trail(ball)",
        "trail.config.interval = 15",
        "",
        "const rod = new EIGHT.Cylinder()",
        "rod.name = 'rod'",
        "rod.color = EIGHT.Color.magenta",
        "rod.radius = 0.5",
        "rod.length = 0.2",
        "rod.position = -1.2 * e1",
        "scene.add(rod)",
        "",
        "const stats = new Stats()",
        "stats.setMode(0)",
        "document.body.appendChild(stats.domElement)",
        "",
        "/**",
        " * The rotational velocity vector.",
        " */",
        "const ω = 2 * Math.PI * (1/10) * e1",
        "/**",
        " * The rotational velocity bivector.",
        " */",
        "const Ω = dual(ω)",
        "",
        "/**",
        " * Initializes the WebGL context once the DOM is ready.",
        " */",
        "window.onload = function() {",
        `  const canvas = <HTMLCanvasElement>document.getElementById('${canvasId}')`,
        `  canvas.width = ${width}`,
        `  canvas.height = ${height}`,
        "",
        "  renderer.start(canvas)",
        "",
        "  controls.subscribe(canvas)",
        "",
        "  requestAnimationFrame(animate)",
        "}",
        "",
        "/**",
        " * Animates the scene.",
        " */",
        "function animate(timestamp: number) {",
        "  stats.begin()",
        "  requestAnimationFrame(animate)",
        "",
        "  renderer.clear()",
        "",
        "  controls.update()",
        "",
        "  dirLight.direction.copy(camera.look).sub(camera.position)",
        "",
        "  const t = timestamp * 0.001",
        "",
        "  ball.position = 2 * (cos(t) * e1 + sin(t) * e3)",
        "  trail.snapshot()",
        "",
        "  cube.attitude = exp(-Ω * t/2)",
        "  rod.attitude = exp(Ω * t/2)",
        "",
        "  arrow.position = rod.position",
        "  arrow.axis = rod.axis * 10",
        "",
        "  scene.draw(ambients)",
        "",
        "  trail.draw(ambients)",
        "",
        "  stats.end()",
        "}",
        "",
        "/**",
        " * Free WebGL resources when the window is unloaded.",
        " */",
        "window.onunload = function() {",
        "",
        "    controls.release()",
        "    renderer.release()",
        "    scene.release()",
        "    trail.release()",
        "",
        "    arrow.release()",
        "    ball.release()",
        "    cube.release()",
        "    rod.release()",
        "",
        "    EIGHT.refChange('stop')",
        "    EIGHT.refChange('dump')",
        "}",
        ""
        ]
    return lines.join('\n')
}