export default function(): string {
    const lines: string[] = [
        "//",
        "// Using WARNME helps keep things going in the face of errors.",
        "//",
        "EIGHT.errorMode = EIGHT.ErrorMode.WARNME",
        "",
        "//",
        "// Basis elements",
        "//",
        "const zero = EIGHT.Geometric3.zero()",
        "const one = EIGHT.Geometric3.one()",
        "const e1 = EIGHT.Geometric3.e1()",
        "const e2 = EIGHT.Geometric3.e2()",
        "const e3 = EIGHT.Geometric3.e3()",
        "",
        "/**",
        " * The pseudoscalar for Euclidean 3D Geometric Space.",
        " */",
        "const I  = e1 ^ e2 ^ e3",
        "",
        "//",
        "// Universal functions",
        "//",
        "const exp = EIGHT.exp",
        "const log = EIGHT.log",
        "const cos = EIGHT.cos",
        "const sin = EIGHT.sin",
        "",
        "//",
        "// Constants",
        "//",
        "/**",
        " * A complete turn, 2 * π.",
        " */",
        "const τ = 2 * Math.PI",
        "",
        "//",
        "// Colors",
        "//",
        "const black = EIGHT.Color.black",
        "const blue = EIGHT.Color.blue",
        "const cyan = EIGHT.Color.cyan",
        "const gray = EIGHT.Color.gray",
        "const green = EIGHT.Color.green",
        "const magenta = EIGHT.Color.magenta",
        "const red = EIGHT.Color.red",
        "const white = EIGHT.Color.white",
        "const yellow = EIGHT.Color.yellow",
        ""
        ]
    return lines.join('\n');
}
