// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/2e7a477ac2b6471055aa6e0e56b333e8f327d6b7/jade/jade.d.ts
// Type definitions for jade
// Project: https://github.com/jadejs/jade
// Definitions by: Panu Horsmalahti <https://github.com/panuhorsmalahti>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

declare module 'jade' {
    export function compile(template: string, options?: any): (locals?: any) => string;
    export function compileFile(path: string, options?: any): (locals?: any) => string;
    export function compileClient(template: string, options?: any): (locals?: any) => string;
    export function compileClientWithDependenciesTracked(template: string, options?: any): {
        body: (locals?: any) => string;
        dependencies: string[];
    };
    export function render(template: string, options?: any): string;
    export function renderFile(path: string, options?: any): string;
}